name: Makefile CI

on:
  push:
    branches: [ "2.12" ]
  pull_request:
    branches: [ "2.12" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build iso
      run:  make iso
